<a href="https://colab.research.google.com/github/yoeda11/Ddd/blob/main/As_new.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

filepath = "/content/drive/MyDrive/Colab Notebooks/AnalisisSentimen/AnalisisSentimen_3/Dataset/comments.csv"
yt = pd.read_csv(filepath)
yt.head()

                                             comment
0  buat driver amd, pengalaman jujur cuma sekali ...
1  Gpu AMD terlalu ngebut bang sampe begituan dit...
2  Editing rendering nya besok dimasukin bang, ka...
3  Saya pernah pake pc dengan 2 vga tersebut di a...
4  makasih banget videonya ini ngebantu buat nent...

**Preprocessing**

In [3]:
# Case Folding
# Mengubah semua teks menjadi huruf kecil.
yt["case_folding"] = yt["comment"].str.lower()
yt.head()

,comment,case_folding
0,"buat driver amd, pengalaman jujur cuma sekali ...","buat driver amd, pengalaman jujur cuma sekali ..."
1,Gpu AMD terlalu ngebut bang sampe begituan dit...,gpu amd terlalu ngebut bang sampe begituan dit...
2,"Editing rendering nya besok dimasukin bang, ka...","editing rendering nya besok dimasukin bang, ka..."
3,Saya pernah pake pc dengan 2 vga tersebut di a...,saya pernah pake pc dengan 2 vga tersebut di a...
4,makasih banget videonya ini ngebantu buat nent...,makasih banget videonya ini ngebantu buat nent...

In [5]:
# Cleaning (Pembersihan Teks)
# Menghapus elemen yang tidak relevan

import re
def clean_text(text):
  # Handle missing / non-string
  if not isinstance(text, str):
    return ""

  # 1. Case Folding
  # text = text.lower() # sudah ada di atas

  # 2. Hapus URL
  text = re.sub(r"https?://\S+|www\.\S+", " ", text)

  # 3. Hapus mention & hashtag
  text = re.sub(r"@\w+|#\w+", " ", text)

  # 4. Hapus angka
  text = re.sub(r"\d+", " ", text)

  # 5. Hapus emoji
  text = re.sub(
      r"["
      u"\U0001F600-\U0001F64F" # emoticon
      u"\U0001F300-\U0001F5FF" # simbol & pictograph
      u"\U0001F680-\U0001F6FF" # transport
      u"\U0001F1E0-\U0001F1FF" # bendera
      "]+",
      " ",
      text
  )

  # 6. Hapus tanda baca & karakter khusus
  text = re.sub(r"[^a-z\s]", " ", text)

  # 7. Hapus karakter non-ASCII (opsional)
  text = text.encode("ascii", "ignore").decode("ascii")

  # 8. Normalisasi spasi
  text = re.sub(r"\s+", " ", text).strip()

  return text

yt["hasil_normalisasi"] = yt["comment"].apply(clean_text)
yt.head()

,comment,case_folding,hasil_normalisasi
0,"buat driver amd, pengalaman jujur cuma sekali ...","buat driver amd, pengalaman jujur cuma sekali ...",buat driver amd pengalaman jujur cuma sekali d...
1,Gpu AMD terlalu ngebut bang sampe begituan dit...,gpu amd terlalu ngebut bang sampe begituan dit...,pu terlalu ngebut bang sampe begituan ditingga...
2,"Editing rendering nya besok dimasukin bang, ka...","editing rendering nya besok dimasukin bang, ka...",diting rendering nya besok dimasukin bang kare...
3,Saya pernah pake pc dengan 2 vga tersebut di a...,saya pernah pake pc dengan 2 vga tersebut di a...,aya pernah pake pc dengan vga tersebut di acar...
4,makasih banget videonya ini ngebantu buat nent...,makasih banget videonya ini ngebantu buat nent...,makasih banget videonya ini ngebantu buat nent...

In [6]:
# Tokenization
# Memecah kalimat menjadi kata-kata (token)
# tokenized_commyt = yt["comment"].apply(lambda x: x.split())
# tokenized_commyt.head(50)

yt["hasil_token"] = yt["comment"].apply(lambda x: x.split())
yt.head(50)

,comment,case_folding,hasil_normalisasi,hasil_token
0,"buat driver amd, pengalaman jujur cuma sekali ...","buat driver amd, pengalaman jujur cuma sekali ...",buat driver amd pengalaman jujur cuma sekali d...,"[buat, driver, amd,, pengalaman, jujur, cuma, ..."
1,Gpu AMD terlalu ngebut bang sampe begituan dit...,gpu amd terlalu ngebut bang sampe begituan dit...,pu terlalu ngebut bang sampe begituan ditingga...,"[Gpu, AMD, terlalu, ngebut, bang, sampe, begit..."
2,"Editing rendering nya besok dimasukin bang, ka...","editing rendering nya besok dimasukin bang, ka...",diting rendering nya besok dimasukin bang kare...,"[Editing, rendering, nya, besok, dimasukin, ba..."
3,Saya pernah pake pc dengan 2 vga tersebut di a...,saya pernah pake pc dengan 2 vga tersebut di a...,aya pernah pake pc dengan vga tersebut di acar...,"[Saya, pernah, pake, pc, dengan, 2, vga, terse..."
4,makasih banget videonya ini ngebantu buat nent...,makasih banget videonya ini ngebantu buat nent...,makasih banget videonya ini ngebantu buat nent...,"[makasih, banget, videonya, ini, ngebantu, bua..."
5,"Udah kapok beli VGA AMD, udah 2 unit jadi bang...","udah kapok beli vga amd, udah 2 unit jadi bang...",dah kapok beli udah unit jadi bangkai yang sat...,"[Udah, kapok, beli, VGA, AMD,, udah, 2, unit, ..."
6,saya sudah pke kedua brand\ndan mnrt saya yg k...,saya sudah pke kedua brand\ndan mnrt saya yg k...,saya sudah pke kedua brand dan mnrt saya yg ke...,"[saya, sudah, pke, kedua, brand, dan, mnrt, sa..."
7,Kelebihan Nvidia lebih bagus untuk gaming dan ...,kelebihan nvidia lebih bagus untuk gaming dan ...,elebihan vidia lebih bagus untuk gaming dan pr...,"[Kelebihan, Nvidia, lebih, bagus, untuk, gamin..."
8,Karena saya jarang menggunakan PC untuk editin...,karena saya jarang menggunakan pc untuk editin...,arena saya jarang menggunakan untuk editing ka...,"[Karena, saya, jarang, menggunakan, PC, untuk,..."
9,gimana dengan kubu biru bang?,gimana dengan kubu biru bang?,gimana dengan kubu biru bang,"[gimana, dengan, kubu, biru, bang?]"
10,"07:06 sama, ngalamin juga bang, driver baru ka...","07:06 sama, ngalamin juga bang, driver baru ka...",sama ngalamin juga bang driver baru kayak gitu...,"[07:06, sama,, ngalamin, juga, bang,, driver, ..."
11,"Rx 6600xt maen game, edit video ... ga pernah ...","rx 6600xt maen game, edit video ... ga pernah ...",x xt maen game edit video ga pernah crash ga n...,"[Rx, 6600xt, maen, game,, edit, video, ..., ga..."
12,aku pilih full kubu merah,aku pilih full kubu merah,aku pilih full kubu merah,"[aku, pilih, full, kubu, merah]"
13,Apa itu radeon? 🤡,apa itu radeon? 🤡,pa itu radeon,"[Apa, itu, radeon?, 🤡]"
14,Gw user amd r3200g amd dan driver error itu em...,gw user amd r3200g amd dan driver error itu em...,w user amd r g amd dan driver error itu emg se...,"[Gw, user, amd, r3200g, amd, dan, driver, erro..."
15,Gue sebagai pengembang bagian desainer Santa M...,gue sebagai pengembang bagian desainer santa m...,ue sebagai pengembang bagian desainer anta oni...,"[Gue, sebagai, pengembang, bagian, desainer, S..."
16,om numpang koment yah...\nmenurut AMD kalau ma...,om numpang koment yah...\nmenurut amd kalau ma...,om numpang koment yah menurut kalau main game ...,"[om, numpang, koment, yah..., menurut, AMD, ka..."
17,"Klo fokus di gaming dan budget bs ke amd aja, ...","klo fokus di gaming dan budget bs ke amd aja, ...",lo fokus di gaming dan budget bs ke amd aja kl...,"[Klo, fokus, di, gaming, dan, budget, bs, ke, ..."
18,"Udah muak gua dgn BUGNYA AMD, akhirnya pindah ...","udah muak gua dgn bugnya amd, akhirnya pindah ...",dah muak gua dgn akhirnya pindah ke vidia ti,"[Udah, muak, gua, dgn, BUGNYA, AMD,, akhirnya,..."
19,"gak perlu dibanding2 pokoknya NVIDIA titik,","gak perlu dibanding2 pokoknya nvidia titik,",gak perlu dibanding pokoknya titik,"[gak, perlu, dibanding2, pokoknya, NVIDIA, tit..."
20,Mending beli mie ayam,mending beli mie ayam,ending beli mie ayam,"[Mending, beli, mie, ayam]"
21,Boros mana?,boros mana?,oros mana,"[Boros, mana?]"
22,kebutuhan game dan budget mepet ambil radeon,kebutuhan game dan budget mepet ambil radeon,kebutuhan game dan budget mepet ambil radeon,"[kebutuhan, game, dan, budget, mepet, ambil, r..."
23,"Buat perbandingan gaming, terutama untuk game ...","buat perbandingan gaming, terutama untuk game ...",uat perbandingan gaming terutama untuk game ba...,"[Buat, perbandingan, gaming,, terutama, untuk,..."
24,"DLSS sih emang masih lebih bagus dari FSR, \n\...","dlss sih emang masih lebih bagus dari fsr, \n\...",sih emang masih lebih bagus dari w juga ketika...,"[DLSS, sih, emang, masih, lebih, bagus, dari, ..."
25,Semua balik ke kebutuhan dan budget ya sobat 😁🙏,semua balik ke kebutuhan dan budget ya sobat 😁🙏,emua balik ke kebutuhan dan budget ya sobat,"[Semua, balik, ke, kebutuhan, dan, budget, ya,..."
26,"Paying more just for Ray Tracing, where the cu...","paying more just for ray tracing, where the cu...",aying more just for ay racing where the curren...,"[Paying, more, just, for, Ray, Tracing,, where..."
27,Aslinya yg pantes head to head rx 7800xt ya yg...,aslinya yg pantes head to head rx 7800xt ya yg...,slinya yg pantes head to head rx xt ya yg ti s...,"[Aslinya, yg, pantes, head, to, head, rx, 7800..."
28,Tpi sekarang amd udah angkat bendera putih bua...,tpi sekarang amd udah angkat bendera putih bua...,pi sekarang amd udah angkat bendera putih buat...,"[Tpi, sekarang, amd, udah, angkat, bendera, pu..."
29,bang mau aku beli dong 6750 nya,bang mau aku beli dong 6750 nya,bang mau aku beli dong nya,"[bang, mau, aku, beli, dong, 6750, nya]"
30,"udah tau pilihan gw apa, pusing duitnya aja ga...","udah tau pilihan gw apa, pusing duitnya aja ga...",udah tau pilihan gw apa pusing duitnya aja ga ...,"[udah, tau, pilihan, gw, apa,, pusing, duitnya..."
31,buat gw sih malah lagi2 balik ke amd....\nhari...,buat gw sih malah lagi2 balik ke amd....\nhari...,buat gw sih malah lagi balik ke amd harian bua...,"[buat, gw, sih, malah, lagi2, balik, ke, amd....."
32,Kalo intel vs ryzen?,kalo intel vs ryzen?,alo intel vs ryzen,"[Kalo, intel, vs, ryzen?]"
33,andaikan hanya ada merk nvidia tanpa ada radeo...,andaikan hanya ada merk nvidia tanpa ada radeo...,andaikan hanya ada merk nvidia tanpa ada radeo...,"[andaikan, hanya, ada, merk, nvidia, tanpa, ad..."
34,Amd utk yf budgrt pas pasan\n\n\nUtk warna gam...,amd utk yf budgrt pas pasan\n\n\nutk warna gam...,md utk yf budgrt pas pasan tk warna gaming dgn...,"[Amd, utk, yf, budgrt, pas, pasan, Utk, warna,..."
35,NVIDIA donks.. irit listrik wkkwk,nvidia donks.. irit listrik wkkwk,donks irit listrik wkkwk,"[NVIDIA, donks.., irit, listrik, wkkwk]"
36,Yang penting ada tulisan rtx🗿,yang penting ada tulisan rtx🗿,ang penting ada tulisan rtx,"[Yang, penting, ada, tulisan, rtx🗿]"
37,Kalo untuk livestream game worth it mana:,kalo untuk livestream game worth it mana:,alo untuk livestream game worth it mana,"[Kalo, untuk, livestream, game, worth, it, mana:]"
38,Udah pasti bagus NVDIA secara Overall kalau se...,udah pasti bagus nvdia secara overall kalau se...,dah pasti bagus secara verall kalau seri s kea...,"[Udah, pasti, bagus, NVDIA, secara, Overall, k..."
39,lebih menarik rtx 4070 super nya zotac di 9.4jt,lebih menarik rtx 4070 super nya zotac di 9.4jt,lebih menarik rtx super nya zotac di jt,"[lebih, menarik, rtx, 4070, super, nya, zotac,..."
40,rekomendasi build pc bang utk kaum sobat PLN 😂...,rekomendasi build pc bang utk kaum sobat pln 😂...,rekomendasi build pc bang utk kaum sobat druma...,"[rekomendasi, build, pc, bang, utk, kaum, soba..."
41,yang kofigurasi PC'nya proci AMD dan VGA'nya n...,yang kofigurasi pc'nya proci amd dan vga'nya n...,yang kofigurasi nya proci dan nya nvidia sini ...,"[yang, kofigurasi, PC'nya, proci, AMD, dan, VG..."
42,setuju sih kalo fsr gak akan bisa kalahin dlss...,setuju sih kalo fsr gak akan bisa kalahin dlss...,setuju sih kalo fsr gak akan bisa kalahin dlss...,"[setuju, sih, kalo, fsr, gak, akan, bisa, kala..."
43,"Pengenya sih support Radeon biar gak tumbang, ...","pengenya sih support radeon biar gak tumbang, ...",engenya sih support adeon biar gak tumbang tap...,"[Pengenya, sih, support, Radeon, biar, gak, tu..."
44,Info dong RTX 4070 yg pake 8 pin power vs 16 p...,info dong rtx 4070 yg pake 8 pin power vs 16 p...,nfo dong yg pake pin power vs pin power untuk ...,"[Info, dong, RTX, 4070, yg, pake, 8, pin, powe..."
45,Sebenanrya ga usah bingung apa sampe dibanding...,sebenanrya ga usah bingung apa sampe dibanding...,ebenanrya ga usah bingung apa sampe dibandingi...,"[Sebenanrya, ga, usah, bingung, apa, sampe, di..."
46,"Suka kubu merah karena price to performance, a...","suka kubu merah karena price to performance, a...",uka kubu merah karena price to performance amb...,"[Suka, kubu, merah, karena, price, to, perform..."
47,Belum nyoba mod dlss enabler bang ? bisa bikin...,belum nyoba mod dlss enabler bang ? bisa bikin...,elum nyoba mod dlss enabler bang bisa bikin at...,"[Belum, nyoba, mod, dlss, enabler, bang, ?, bi..."
48,Performance hanyalah angka. \nmau kubu hijau /...,performance hanyalah angka. \nmau kubu hijau /...,erformance hanyalah angka mau kubu hijau merah...,"[Performance, hanyalah, angka., mau, kubu, hij..."
49,gw penjual pc gaming dari 2012 rekomendasi unt...,gw penjual pc gaming dari 2012 rekomendasi unt...,gw penjual pc gaming dari rekomendasi untuk te...,"[gw, penjual, pc, gaming, dari, 2012, rekomend..."

In [9]:
# Normalization (Normalisasi Kata)
# Mengubah kata tidak baku/slang menjadi baku

# Load kamus slang dari file csv
slang_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/AnalisisSentimen/AnalisisSentimen_3/Dataset/slangindo/slang_indonesia.csv")
slang_dict = dict(zip(slang_df["slang"], slang_df["formal"]))

def normalized_text(tokens):
  return [slang_dict[word] if word in slang_dict else word for word in tokens]

# normalized_commyt = tokenized_commyt.apply(normalized_text)
# normalized_commyt.head(50)

yt["comment"] = yt["comment"].apply(normalized_text)
yt.head(50)

,comment,case_folding,hasil_normalisasi,hasil_token
0,"[b, kamu, a, t, , di, r, i, v, e, r, , a, m,...","buat driver amd, pengalaman jujur cuma sekali ...","[b, kamu, a, t, , di, r, i, v, e, r, , a, m,...","[buat, driver, amd,, pengalaman, jujur, cuma, ..."
1,"[G, p, kamu, , A, M, D, , t, e, r, l, a, l, ...",gpu amd terlalu ngebut bang sampe begituan dit...,"[G, p, kamu, , A, M, D, , t, e, r, l, a, l, ...","[Gpu, AMD, terlalu, ngebut, bang, sampe, begit..."
2,"[E, di, i, t, i, n, tidak, , r, e, n, di, e, ...","editing rendering nya besok dimasukin bang, ka...","[E, di, i, t, i, n, tidak, , r, e, n, di, e, ...","[Editing, rendering, nya, besok, dimasukin, ba..."
3,"[S, a, nya, a, , p, e, r, n, a, h, , p, a, k...",saya pernah pake pc dengan 2 vga tersebut di a...,"[S, a, nya, a, , p, e, r, n, a, h, , p, a, k...","[Saya, pernah, pake, pc, dengan, 2, vga, terse..."
4,"[m, a, ke, a, sih, i, h, , b, a, n, tidak, e,...",makasih banget videonya ini ngebantu buat nent...,"[m, a, ke, a, sih, i, h, , b, a, n, tidak, e,...","[makasih, banget, videonya, ini, ngebantu, bua..."
5,"[U, di, a, h, , ke, a, p, o, ke, , b, e, l, ...","udah kapok beli vga amd, udah 2 unit jadi bang...","[U, di, a, h, , ke, a, p, o, ke, , b, e, l, ...","[Udah, kapok, beli, VGA, AMD,, udah, 2, unit, ..."
6,"[sih, a, nya, a, , sih, kamu, di, a, h, , p,...",saya sudah pke kedua brand\ndan mnrt saya yg k...,"[sih, a, nya, a, , sih, kamu, di, a, h, , p,...","[saya, sudah, pke, kedua, brand, dan, mnrt, sa..."
7,"[K, e, l, e, b, i, h, a, n, , N, v, i, di, i,...",kelebihan nvidia lebih bagus untuk gaming dan ...,"[K, e, l, e, b, i, h, a, n, , N, v, i, di, i,...","[Kelebihan, Nvidia, lebih, bagus, untuk, gamin..."
8,"[K, a, r, e, n, a, , sih, a, nya, a, , saja,...",karena saya jarang menggunakan pc untuk editin...,"[K, a, r, e, n, a, , sih, a, nya, a, , saja,...","[Karena, saya, jarang, menggunakan, PC, untuk,..."
9,"[tidak, i, m, a, n, a, , di, e, n, tidak, a, ...",gimana dengan kubu biru bang?,"[tidak, i, m, a, n, a, , di, e, n, tidak, a, ...","[gimana, dengan, kubu, biru, bang?]"
10,"[0, 7, :, 0, 6, , sih, a, m, a, ,, , n, tida...","07:06 sama, ngalamin juga bang, driver baru ka...","[0, 7, :, 0, 6, , sih, a, m, a, ,, , n, tida...","[07:06, sama,, ngalamin, juga, bang,, driver, ..."
11,"[R, kali, , 6, 6, 0, 0, kali, t, , m, a, e, ...","rx 6600xt maen game, edit video ... ga pernah ...","[R, kali, , 6, 6, 0, 0, kali, t, , m, a, e, ...","[Rx, 6600xt, maen, game,, edit, video, ..., ga..."
12,"[a, ke, kamu, , p, i, l, i, h, , f, kamu, l,...",aku pilih full kubu merah,"[a, ke, kamu, , p, i, l, i, h, , f, kamu, l,...","[aku, pilih, full, kubu, merah]"
13,"[A, p, a, , i, t, kamu, , r, a, di, e, o, n,...",apa itu radeon? 🤡,"[A, p, a, , i, t, kamu, , r, a, di, e, o, n,...","[Apa, itu, radeon?, 🤡]"
14,"[G, saya, , kamu, sih, e, r, , a, m, di, , ...",gw user amd r3200g amd dan driver error itu em...,"[G, saya, , kamu, sih, e, r, , a, m, di, , ...","[Gw, user, amd, r3200g, amd, dan, driver, erro..."
15,"[G, kamu, e, , sih, e, b, a, tidak, a, i, , ...",gue sebagai pengembang bagian desainer santa m...,"[G, kamu, e, , sih, e, b, a, tidak, a, i, , ...","[Gue, sebagai, pengembang, bagian, desainer, S..."
16,"[o, m, , n, kamu, m, p, a, n, tidak, , ke, o...",om numpang koment yah...\nmenurut amd kalau ma...,"[o, m, , n, kamu, m, p, a, n, tidak, , ke, o...","[om, numpang, koment, yah..., menurut, AMD, ka..."
17,"[K, l, o, , f, o, ke, kamu, sih, , di, i, ,...","klo fokus di gaming dan budget bs ke amd aja, ...","[K, l, o, , f, o, ke, kamu, sih, , di, i, ,...","[Klo, fokus, di, gaming, dan, budget, bs, ke, ..."
18,"[U, di, a, h, , m, kamu, a, ke, , tidak, kam...","udah muak gua dgn bugnya amd, akhirnya pindah ...","[U, di, a, h, , m, kamu, a, ke, , tidak, kam...","[Udah, muak, gua, dgn, BUGNYA, AMD,, akhirnya,..."
19,"[tidak, a, ke, , p, e, r, l, kamu, , di, i, ...","gak perlu dibanding2 pokoknya nvidia titik,","[tidak, a, ke, , p, e, r, l, kamu, , di, i, ...","[gak, perlu, dibanding2, pokoknya, NVIDIA, tit..."
20,"[M, e, n, di, i, n, tidak, , b, e, l, i, , m...",mending beli mie ayam,"[M, e, n, di, i, n, tidak, , b, e, l, i, , m...","[Mending, beli, mie, ayam]"
21,"[B, o, r, o, sih, , m, a, n, a, ?]",boros mana?,"[B, o, r, o, sih, , m, a, n, a, ?]","[Boros, mana?]"
22,"[ke, e, b, kamu, t, kamu, h, a, n, , tidak, a...",kebutuhan game dan budget mepet ambil radeon,"[ke, e, b, kamu, t, kamu, h, a, n, , tidak, a...","[kebutuhan, game, dan, budget, mepet, ambil, r..."
23,"[B, kamu, a, t, , p, e, r, b, a, n, di, i, n,...","buat perbandingan gaming, terutama untuk game ...","[B, kamu, a, t, , p, e, r, b, a, n, di, i, n,...","[Buat, perbandingan, gaming,, terutama, untuk,..."
24,"[D, L, S, S, , sih, i, h, , e, m, a, n, tida...","dlss sih emang masih lebih bagus dari fsr, \n\...","[D, L, S, S, , sih, i, h, , e, m, a, n, tida...","[DLSS, sih, emang, masih, lebih, bagus, dari, ..."
25,"[S, e, m, kamu, a, , b, a, l, i, ke, , ke, e...",semua balik ke kebutuhan dan budget ya sobat 😁🙏,"[S, e, m, kamu, a, , b, a, l, i, ke, , ke, e...","[Semua, balik, ke, kebutuhan, dan, budget, ya,..."
26,"[P, a, nya, i, n, tidak, , m, o, r, e, , saj...","paying more just for ray tracing, where the cu...","[P, a, nya, i, n, tidak, , m, o, r, e, , saj...","[Paying, more, just, for, Ray, Tracing,, where..."
27,"[A, sih, l, i, n, nya, a, , nya, tidak, , p,...",aslinya yg pantes head to head rx 7800xt ya yg...,"[A, sih, l, i, n, nya, a, , nya, tidak, , p,...","[Aslinya, yg, pantes, head, to, head, rx, 7800..."
28,"[T, p, i, , sih, e, ke, a, r, a, n, tidak, ,...",tpi sekarang amd udah angkat bendera putih bua...,"[T, p, i, , sih, e, ke, a, r, a, n, tidak, ,...","[Tpi, sekarang, amd, udah, angkat, bendera, pu..."
29,"[b, a, n, tidak, , m, a, kamu, , a, ke, kamu...",bang mau aku beli dong 6750 nya,"[b, a, n, tidak, , m, a, kamu, , a, ke, kamu...","[bang, mau, aku, beli, dong, 6750, nya]"
30,"[kamu, di, a, h, , t, a, kamu, , p, i, l, i,...","udah tau pilihan gw apa, pusing duitnya aja ga...","[kamu, di, a, h, , t, a, kamu, , p, i, l, i,...","[udah, tau, pilihan, gw, apa,, pusing, duitnya..."
31,"[b, kamu, a, t, , tidak, saya, , sih, i, h, ...",buat gw sih malah lagi2 balik ke amd....\nhari...,"[b, kamu, a, t, , tidak, saya, , sih, i, h, ...","[buat, gw, sih, malah, lagi2, balik, ke, amd....."
32,"[K, a, l, o, , i, n, t, e, l, , v, sih, , r...",kalo intel vs ryzen?,"[K, a, l, o, , i, n, t, e, l, , v, sih, , r...","[Kalo, intel, vs, ryzen?]"
33,"[a, n, di, a, i, ke, a, n, , h, a, n, nya, a,...",andaikan hanya ada merk nvidia tanpa ada radeo...,"[a, n, di, a, i, ke, a, n, , h, a, n, nya, a,...","[andaikan, hanya, ada, merk, nvidia, tanpa, ad..."
34,"[A, m, di, , kamu, t, ke, , nya, f, , b, ka...",amd utk yf budgrt pas pasan\n\n\nutk warna gam...,"[A, m, di, , kamu, t, ke, , nya, f, , b, ka...","[Amd, utk, yf, budgrt, pas, pasan, Utk, warna,..."
35,"[N, V, I, D, I, A, , di, o, n, ke, sih, ., .,...",nvidia donks.. irit listrik wkkwk,"[N, V, I, D, I, A, , di, o, n, ke, sih, ., .,...","[NVIDIA, donks.., irit, listrik, wkkwk]"
36,"[Y, a, n, tidak, , p, e, n, t, i, n, tidak, ...",yang penting ada tulisan rtx🗿,"[Y, a, n, tidak, , p, e, n, t, i, n, tidak, ...","[Yang, penting, ada, tulisan, rtx🗿]"
37,"[K, a, l, o, , kamu, n, t, kamu, ke, , l, i,...",kalo untuk livestream game worth it mana:,"[K, a, l, o, , kamu, n, t, kamu, ke, , l, i,...","[Kalo, untuk, livestream, game, worth, it, mana:]"
38,"[U, di, a, h, , p, a, sih, t, i, , b, a, tid...",udah pasti bagus nvdia secara overall kalau se...,"[U, di, a, h, , p, a, sih, t, i, , b, a, tid...","[Udah, pasti, bagus, NVDIA, secara, Overall, k..."
39,"[l, e, b, i, h, , m, e, n, a, r, i, ke, , r,...",lebih menarik rtx 4070 super nya zotac di 9.4jt,"[l, e, b, i, h, , m, e, n, a, r, i, ke, , r,...","[lebih, menarik, rtx, 4070, super, nya, zotac,..."
40,"[r, e, ke, o, m, e, n, di, a, sih, i, , b, ka...",rekomendasi build pc bang utk kaum sobat pln 😂...,"[r, e, ke, o, m, e, n, di, a, sih, i, , b, ka...","[rekomendasi, build, pc, bang, utk, kaum, soba..."
41,"[nya, a, n, tidak, , ke, o, f, i, tidak, kamu...",yang kofigurasi pc'nya proci amd dan vga'nya n...,"[nya, a, n, tidak, , ke, o, f, i, tidak, kamu...","[yang, kofigurasi, PC'nya, proci, AMD, dan, VG..."
42,"[sih, e, t, kamu, saja, kamu, , sih, i, h, ,...",setuju sih kalo fsr gak akan bisa kalahin dlss...,"[sih, e, t, kamu, saja, kamu, , sih, i, h, ,...","[setuju, sih, kalo, fsr, gak, akan, bisa, kala..."
43,"[P, e, n, tidak, e, n, nya, a, , sih, i, h, ...","pengenya sih support radeon biar gak tumbang, ...","[P, e, n, tidak, e, n, nya, a, , sih, i, h, ...","[Pengenya, sih, support, Radeon, biar, gak, tu..."
44,"[I, n, f, o, , di, o, n, tidak, , R, T, X, ...",info dong rtx 4070 yg pake 8 pin power vs 16 p...,"[I, n, f, o, , di, o, n, tidak, , R, T, X, ...","[Info, dong, RTX, 4070, yg, pake, 8, pin, powe..."
45,"[S, e, b, e, n, a, n, r, nya, a, , tidak, a, ...",sebenanrya ga usah bingung apa sampe dibanding...,"[S, e, b, e, n, a, n, r, nya, a, , tidak, a, ...","[Sebenanrya, ga, usah, bingung, apa, sampe, di..."
46,"[S, kamu, ke, a, , ke, kamu, b, kamu, , m, e...","suka kubu merah karena price to performance, a...","[S, kamu, ke, a, , ke, kamu, b, kamu, , m, e...","[Suka, kubu, merah, karena, price, to, perform..."
47,"[B, e, l, kamu, m, , n, nya, o, b, a, , m, o...",belum nyoba mod dlss enabler bang ? bisa bikin...,"[B, e, l, kamu, m, , n, nya, o, b, a, , m, o...","[Belum, nyoba, mod, dlss, enabler, bang, ?, bi..."
48,"[P, e, r, f, o, r, m, a, n, sih, e, , h, a, n...",performance hanyalah angka. \nmau kubu hijau /...,"[P, e, r, f, o, r, m, a, n, sih, e, , h, a, n...","[Performance, hanyalah, angka., mau, kubu, hij..."
49,"[tidak, saya, , p, e, n, saja, kamu, a, l, ,...",gw penjual pc gaming dari 2012 rekomendasi unt...,"[tidak, saya, , p, e, n, saja, kamu, a, l, ,...","[gw, penjual, pc, gaming, dari, 2012, rekomend..."

In [23]:
!pip install Sastrawi

Requirement already satisfied: Sastrawi in /usr/local/lib/python3.12/dist-packages (1.0.1)

In [24]:
# Stopword Removal
# Menghapus kata yang tidak punya makna penting.
# Contoh stopword:
# "dan", "di", "yang", "ke", "dari"

from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

factory = StopWordRemoverFactory()
stopwords = set(factory.get_stop_words())

In [28]:
negation_words = {
    "tidak", "bukan", "jangan", "belum", "kurang", "tanpan"
}

stopwords = stopwords - negation_words

In [27]:
noise_words = {
    "nya", "sih", "dong", "deh", "kok", "nih", "loh", "ya", "kan", "aja", "pun", "lah"
}

stopwords = stopwords.union(noise_words)

In [29]:
def stopword_removal(tokens):
    filtered = []
    for word in tokens:
        if word not in stopwords and len(word) > 2:
            filtered.append(word)
    return filtered

In [38]:
# stopwords_commyt = normalized_commyt.apply(stopword_removal)
# stopwords_commyt.head(50)

yt["hasil_stopwords"] = yt["comment"].apply(stopword_removal)
yt.head(50)

,comment,label_gpu,hasil_stemming,hasil_stopwords
0,"[buat, driver, amd, alam, jujur, cuma, sekali,...",AMD,"[buat, driver, amd, alam, jujur, cuma, sekali,...","[buat, driver, amd, alam, jujur, cuma, sekali,..."
1,"[gpu, amd, terlalu, ngebut, bang, begitu, diti...",AMD,"[gpu, amd, terlalu, ngebut, bang, begitu, diti...","[gpu, amd, terlalu, ngebut, bang, ditinggalin,..."
2,"[editing, rendering, besok, dimasukin, bang, t...",AMD,"[editing, rendering, besok, dimasukin, bang, t...","[editing, rendering, besok, dimasukin, bang, t..."
3,"[pernah, pakai, vga, sebut, acara, live, wisud...",AMD,"[pernah, pakai, vga, sebut, acara, live, wisud...","[pernah, pakai, vga, sebut, acara, live, wisud..."
4,"[terima kasih, sekali, video, ngebantu, buat, ...",NVIDIA,"[terima kasih, sekali, video, ngebantu, buat, ...","[terima kasih, sekali, video, ngebantu, buat, ..."
5,"[sudah, kapok, beli, vga, amd, sudah, unit, ja...",AMD,"[sudah, kapok, beli, vga, amd, sudah, unit, ja...","[kapok, beli, vga, amd, unit, jadi, bangkai, s..."
6,"[pakai, dua, brand, turut, yang, butuh, pure, ...",NVIDIA,"[pakai, dua, brand, turut, yang, butuh, pure, ...","[pakai, brand, turut, butuh, pure, gaming, bet..."
7,"[lebih, nvidia, lebih, bagus, gaming, professi...",NVIDIA,"[lebih, nvidia, lebih, bagus, gaming, professi...","[lebih, nvidia, lebih, bagus, gaming, professi..."
8,"[jarang, guna, editing, kalaupun, ngedit, pali...",AMD,"[jarang, guna, editing, kalaupun, ngedit, pali...","[jarang, editing, kalaupun, ngedit, paling, cu..."
9,"[bagaimana, kubu, biru, bang]",Lainnya,"[bagaimana, kubu, biru, bang]","[bagaimana, kubu, biru, bang]"
10,"[sama, ngalamin, bang, driver, baru, mirip, be...",Lainnya,"[sama, ngalamin, bang, driver, baru, mirip, be...","[sama, ngalamin, bang, driver, baru, mirip, en..."
11,"[main, game, edit, video, tidak, pernah, crash...",Lainnya,"[main, game, edit, video, tidak, pernah, crash...","[main, game, edit, video, tidak, pernah, crash..."
12,"[pilih, full, kubu, merah]",AMD,"[pilih, full, kubu, merah]","[pilih, full, kubu, merah]"
13,"[apa, radeon]",AMD,"[apa, radeon]","[apa, radeon]"
14,"[user, amd, tidak, amd, driver, error, memang,...",AMD,"[user, amd, tidak, amd, driver, error, memang,...","[user, amd, tidak, amd, driver, error, memang,..."
15,"[kembang, bagi, desainer, santa, monica, pilih...",NVIDIA,"[kembang, bagi, desainer, santa, monica, pilih...","[kembang, desainer, santa, monica, pilih, nvid..."
16,"[numpang, komentar, amd, kalau, main, game, pa...",AMD,"[numpang, komentar, amd, kalau, main, game, pa...","[numpang, komentar, amd, kalau, main, game, pa..."
17,"[kalau, fokus, gaming, budget, bisa, amd, saja...",NVIDIA,"[kalau, fokus, gaming, budget, bisa, amd, saja...","[kalau, fokus, gaming, budget, amd, kalau, hig..."
18,"[sudah, muak, saya, dengan, bugnya, amd, akhir...",NVIDIA,"[sudah, muak, saya, dengan, bugnya, amd, akhir...","[muak, bugnya, amd, akhir, pindah, nvidia]"
19,"[tidak, perlu, banding, pokok, nvidia, titik]",NVIDIA,"[tidak, perlu, banding, pokok, nvidia, titik]","[tidak, perlu, banding, pokok, nvidia, titik]"
20,"[mending, beli, mie, ayam]",Lainnya,"[mending, beli, mie, ayam]","[mending, beli, mie, ayam]"
21,"[boros, mana]",Lainnya,"[boros, mana]","[boros, mana]"
22,"[butuh, game, budget, mepet, ambil, radeon]",AMD,"[butuh, game, budget, mepet, ambil, radeon]","[butuh, game, budget, mepet, ambil, radeon]"
23,"[buat, banding, gaming, utama, game, baru, mac...",NVIDIA,"[buat, banding, gaming, utama, game, baru, mac...","[buat, banding, gaming, utama, game, baru, mac..."
24,"[dlss, memang, lebih, bagus, fsr, maka, fsr, a...",Lainnya,"[dlss, memang, lebih, bagus, fsr, maka, fsr, a...","[dlss, memang, lebih, bagus, fsr, fsr, asa, be..."
25,"[semua, balik, butuh, budget, sobat]",Lainnya,"[semua, balik, butuh, budget, sobat]","[semua, balik, butuh, budget, sobat]"
26,"[paying, more, just, for, ray, tracing, where,...",NVIDIA,"[paying, more, just, for, ray, tracing, where,...","[paying, more, just, for, ray, tracing, where,..."
27,"[asli, yang, pantas, head, head, yang, super, ...",Lainnya,"[asli, yang, pantas, head, head, yang, super, ...","[asli, pantas, head, head, super, bukan, non]"
28,"[tapi, sekarang, amd, sudah, angkat, bendera, ...",NVIDIA,"[tapi, sekarang, amd, sudah, angkat, bendera, ...","[sekarang, amd, angkat, bendera, putih, buat, ..."
29,"[bang, mau, beli]",Lainnya,"[bang, mau, beli]","[bang, mau, beli]"
30,"[sudah, tahu, pilih, apa, pusing, duit, saja, ...",Lainnya,"[sudah, tahu, pilih, apa, pusing, duit, saja, ...","[tahu, pilih, apa, pusing, duit, tidak, bang]"
31,"[buat, malah, balik, amd, hari, buat, gaming, ...",AMD,"[buat, malah, balik, amd, hari, buat, gaming, ...","[buat, malah, balik, amd, hari, buat, gaming, ..."
32,"[kalau, intel, ryzen]",Lainnya,"[kalau, intel, ryzen]","[kalau, intel, ryzen]"
33,"[andai, merk, nvidia, radeon, gpu, nvidia, yan...",NVIDIA,"[andai, merk, nvidia, radeon, gpu, nvidia, yan...","[andai, merk, nvidia, radeon, gpu, nvidia, awa..."
34,"[amd, untuk, budgrt, pas, pas, untuk, warna, g...",NVIDIA,"[amd, untuk, budgrt, pas, pas, untuk, warna, g...","[amd, budgrt, pas, pas, warna, gaming, fitur, ..."
35,"[nvidia, irit, listrik, wkkwk]",NVIDIA,"[nvidia, irit, listrik, wkkwk]","[nvidia, irit, listrik, wkkwk]"
36,"[penting, tulis, rtx]",NVIDIA,"[penting, tulis, rtx]","[penting, tulis, rtx]"
37,"[kalau, livestream, game, worth, mana]",Lainnya,"[kalau, livestream, game, worth, mana]","[kalau, livestream, game, worth, mana]"
38,"[sudah, bagus, nvdia, overall, kalau, seri, at...",NVIDIA,"[sudah, bagus, nvdia, overall, kalau, seri, at...","[bagus, nvdia, overall, kalau, seri, atas, fit..."
39,"[lebih, tarik, rtx, super, zotac, juta]",NVIDIA,"[lebih, tarik, rtx, super, zotac, juta]","[lebih, tarik, rtx, super, zotac, juta]"
40,"[rekomendasi, build, bang, untuk, kaum, sobat,...",Lainnya,"[rekomendasi, build, bang, untuk, kaum, sobat,...","[rekomendasi, build, bang, kaum, sobat, pln, d..."
41,"[kofigurasi, proci, amd, vga, nvidia, sini, ng...",NVIDIA,"[kofigurasi, proci, amd, vga, nvidia, sini, ng...","[kofigurasi, proci, amd, vga, nvidia, sini, ng..."
42,"[tuju, kalau, fsr, tidak, kalahin, dlss, aku, ...",NVIDIA,"[tuju, kalau, fsr, tidak, kalahin, dlss, aku, ...","[tuju, kalau, fsr, tidak, kalahin, dlss, aku, ..."
43,"[kenya, support, radeon, biar, tidak, tumbang,...",NVIDIA,"[kenya, support, radeon, biar, tidak, tumbang,...","[kenya, support, radeon, biar, tidak, tumbang,..."
44,"[info, rtx, yang, pakai, pin, power, pin, powe...",NVIDIA,"[info, rtx, yang, pakai, pin, power, pin, powe...","[info, rtx, pakai, pin, power, pin, power, def..."
45,"[sebenanrya, tidak, usah, bingung, apa, diband...",NVIDIA,"[sebenanrya, tidak, usah, bingung, apa, diband...","[sebenanrya, tidak, usah, bingung, apa, diband..."
46,"[suka, kubu, merah, price, performance, ambil,...",AMD,"[suka, kubu, merah, price, performance, ambil,...","[suka, kubu, merah, price, performance, ambil,..."
47,"[belum, coba, mod, dlss, enabler, bang, bikin,...",NVIDIA,"[belum, coba, mod, dlss, enabler, bang, bikin,...","[belum, coba, mod, dlss, enabler, bang, bikin,..."
48,"[performance, hanya, angka, mau, kubu, hijau, ...",NVIDIA,"[performance, hanya, angka, mau, kubu, hijau, ...","[performance, angka, mau, kubu, hijau, merah, ..."
49,"[jual, gaming, rekomendasi, gpu, tetap, nvidia...",NVIDIA,"[jual, gaming, rekomendasi, gpu, tetap, nvidia...","[jual, gaming, rekomendasi, gpu, tetap, nvidia..."

In [32]:
# Stemming / Lemmatization
# Mengubah kata ke bentuk dasar

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

# Inisialisasi Stemmer
factory = StemmerFactory()
stemmer = factory.create_stemmer()

# Proses Stemming
# stemmer_commyt = stemmer.stem(stopwords_commyt)
# stemmer_commyt = stopwords_commyt.apply(lambda x: stemmer.stem(x))
# stemmer_commyt.head()

In [37]:
# Function / Fungsi Stemmer per token
def stemming_token(tokens):
  return [stemmer.stem(word) for word in tokens]

# stemming_commyt = stopwords_commyt.apply(stemming_token)
# stemming_commyt.head(50)

yt["hasil_stemming"] = yt["comment"].apply(stemming_token)
yt.head(50)

,comment,label_gpu,hasil_stemming
0,"[buat, driver, amd, alam, jujur, cuma, sekali,...",AMD,"[buat, driver, amd, alam, jujur, cuma, sekali,..."
1,"[gpu, amd, terlalu, ngebut, bang, begitu, diti...",AMD,"[gpu, amd, terlalu, ngebut, bang, begitu, diti..."
2,"[editing, rendering, besok, dimasukin, bang, t...",AMD,"[editing, rendering, besok, dimasukin, bang, t..."
3,"[pernah, pakai, vga, sebut, acara, live, wisud...",AMD,"[pernah, pakai, vga, sebut, acara, live, wisud..."
4,"[terima kasih, sekali, video, ngebantu, buat, ...",NVIDIA,"[terima kasih, sekali, video, ngebantu, buat, ..."
5,"[sudah, kapok, beli, vga, amd, sudah, unit, ja...",AMD,"[sudah, kapok, beli, vga, amd, sudah, unit, ja..."
6,"[pakai, dua, brand, turut, yang, butuh, pure, ...",NVIDIA,"[pakai, dua, brand, turut, yang, butuh, pure, ..."
7,"[lebih, nvidia, lebih, bagus, gaming, professi...",NVIDIA,"[lebih, nvidia, lebih, bagus, gaming, professi..."
8,"[jarang, guna, editing, kalaupun, ngedit, pali...",AMD,"[jarang, guna, editing, kalaupun, ngedit, pali..."
9,"[bagaimana, kubu, biru, bang]",Lainnya,"[bagaimana, kubu, biru, bang]"
10,"[sama, ngalamin, bang, driver, baru, mirip, be...",Lainnya,"[sama, ngalamin, bang, driver, baru, mirip, be..."
11,"[main, game, edit, video, tidak, pernah, crash...",Lainnya,"[main, game, edit, video, tidak, pernah, crash..."
12,"[pilih, full, kubu, merah]",AMD,"[pilih, full, kubu, merah]"
13,"[apa, radeon]",AMD,"[apa, radeon]"
14,"[user, amd, tidak, amd, driver, error, memang,...",AMD,"[user, amd, tidak, amd, driver, error, memang,..."
15,"[kembang, bagi, desainer, santa, monica, pilih...",NVIDIA,"[kembang, bagi, desainer, santa, monica, pilih..."
16,"[numpang, komentar, amd, kalau, main, game, pa...",AMD,"[numpang, komentar, amd, kalau, main, game, pa..."
17,"[kalau, fokus, gaming, budget, bisa, amd, saja...",NVIDIA,"[kalau, fokus, gaming, budget, bisa, amd, saja..."
18,"[sudah, muak, saya, dengan, bugnya, amd, akhir...",NVIDIA,"[sudah, muak, saya, dengan, bugnya, amd, akhir..."
19,"[tidak, perlu, banding, pokok, nvidia, titik]",NVIDIA,"[tidak, perlu, banding, pokok, nvidia, titik]"
20,"[mending, beli, mie, ayam]",Lainnya,"[mending, beli, mie, ayam]"
21,"[boros, mana]",Lainnya,"[boros, mana]"
22,"[butuh, game, budget, mepet, ambil, radeon]",AMD,"[butuh, game, budget, mepet, ambil, radeon]"
23,"[buat, banding, gaming, utama, game, baru, mac...",NVIDIA,"[buat, banding, gaming, utama, game, baru, mac..."
24,"[dlss, memang, lebih, bagus, fsr, maka, fsr, a...",Lainnya,"[dlss, memang, lebih, bagus, fsr, maka, fsr, a..."
25,"[semua, balik, butuh, budget, sobat]",Lainnya,"[semua, balik, butuh, budget, sobat]"
26,"[paying, more, just, for, ray, tracing, where,...",NVIDIA,"[paying, more, just, for, ray, tracing, where,..."
27,"[asli, yang, pantas, head, head, yang, super, ...",Lainnya,"[asli, yang, pantas, head, head, yang, super, ..."
28,"[tapi, sekarang, amd, sudah, angkat, bendera, ...",NVIDIA,"[tapi, sekarang, amd, sudah, angkat, bendera, ..."
29,"[bang, mau, beli]",Lainnya,"[bang, mau, beli]"
30,"[sudah, tahu, pilih, apa, pusing, duit, saja, ...",Lainnya,"[sudah, tahu, pilih, apa, pusing, duit, saja, ..."
31,"[buat, malah, balik, amd, hari, buat, gaming, ...",AMD,"[buat, malah, balik, amd, hari, buat, gaming, ..."
32,"[kalau, intel, ryzen]",Lainnya,"[kalau, intel, ryzen]"
33,"[andai, merk, nvidia, radeon, gpu, nvidia, yan...",NVIDIA,"[andai, merk, nvidia, radeon, gpu, nvidia, yan..."
34,"[amd, untuk, budgrt, pas, pas, untuk, warna, g...",NVIDIA,"[amd, untuk, budgrt, pas, pas, untuk, warna, g..."
35,"[nvidia, irit, listrik, wkkwk]",NVIDIA,"[nvidia, irit, listrik, wkkwk]"
36,"[penting, tulis, rtx]",NVIDIA,"[penting, tulis, rtx]"
37,"[kalau, livestream, game, worth, mana]",Lainnya,"[kalau, livestream, game, worth, mana]"
38,"[sudah, bagus, nvdia, overall, kalau, seri, at...",NVIDIA,"[sudah, bagus, nvdia, overall, kalau, seri, at..."
39,"[lebih, tarik, rtx, super, zotac, juta]",NVIDIA,"[lebih, tarik, rtx, super, zotac, juta]"
40,"[rekomendasi, build, bang, untuk, kaum, sobat,...",Lainnya,"[rekomendasi, build, bang, untuk, kaum, sobat,..."
41,"[kofigurasi, proci, amd, vga, nvidia, sini, ng...",NVIDIA,"[kofigurasi, proci, amd, vga, nvidia, sini, ng..."
42,"[tuju, kalau, fsr, tidak, kalahin, dlss, aku, ...",NVIDIA,"[tuju, kalau, fsr, tidak, kalahin, dlss, aku, ..."
43,"[kenya, support, radeon, biar, tidak, tumbang,...",NVIDIA,"[kenya, support, radeon, biar, tidak, tumbang,..."
44,"[info, rtx, yang, pakai, pin, power, pin, powe...",NVIDIA,"[info, rtx, yang, pakai, pin, power, pin, powe..."
45,"[sebenanrya, tidak, usah, bingung, apa, diband...",NVIDIA,"[sebenanrya, tidak, usah, bingung, apa, diband..."
46,"[suka, kubu, merah, price, performance, ambil,...",AMD,"[suka, kubu, merah, price, performance, ambil,..."
47,"[belum, coba, mod, dlss, enabler, bang, bikin,...",NVIDIA,"[belum, coba, mod, dlss, enabler, bang, bikin,..."
48,"[performance, hanya, angka, mau, kubu, hijau, ...",NVIDIA,"[performance, hanya, angka, mau, kubu, hijau, ..."
49,"[jual, gaming, rekomendasi, gpu, tetap, nvidia...",NVIDIA,"[jual, gaming, rekomendasi, gpu, tetap, nvidia..."

In [34]:
def label_gpu(text):
  if "nvidia" in text or "rtx" in text or "gtx" in text or "hijau" in text:
    return "NVIDIA"
  elif "amd" in text or "radeon" in text or "merah" in text:
    return "AMD"
  else:
    return "Lainnya"

# label_commyt = stemming_commyt.apply(label_gpu)
# label_commyt.head(25)

# stemming_commyt["label_gpu"] = stemming_commyt["comment"].apply(label_gpu)
# stemming_commyt.head(25)
yt["label_gpu"] = yt["comment"].apply(label_gpu)
yt.head(25)

                                              comment label_gpu
0   [buat, driver, amd, alam, jujur, cuma, sekali,...       AMD
1   [gpu, amd, terlalu, ngebut, bang, begitu, diti...       AMD
2   [editing, rendering, besok, dimasukin, bang, t...       AMD
3   [pernah, pakai, vga, sebut, acara, live, wisud...       AMD
4   [terima kasih, sekali, video, ngebantu, buat, ...    NVIDIA
5   [sudah, kapok, beli, vga, amd, sudah, unit, ja...       AMD
6   [pakai, dua, brand, turut, yang, butuh, pure, ...    NVIDIA
7   [lebih, nvidia, lebih, bagus, gaming, professi...    NVIDIA
8   [jarang, guna, editing, kalaupun, ngedit, pali...       AMD
9                       [bagaimana, kubu, biru, bang]   Lainnya
10  [sama, ngalamin, bang, driver, baru, mirip, be...   Lainnya
11  [main, game, edit, video, tidak, pernah, crash...   Lainnya
12                         [pilih, full, kubu, merah]       AMD
13                                      [apa, radeon]       AMD
14  [user, amd, tidak, amd, driver, error, memang,...       AMD
15  [kembang, bagi, desainer, santa, monica, pilih...    NVIDIA
16  [numpang, komentar, amd, kalau, main, game, pa...       AMD
17  [kalau, fokus, gaming, budget, bisa, amd, saja...    NVIDIA
18  [sudah, muak, saya, dengan, bugnya, amd, akhir...    NVIDIA
19      [tidak, perlu, banding, pokok, nvidia, titik]    NVIDIA
20                         [mending, beli, mie, ayam]   Lainnya
21                                      [boros, mana]   Lainnya
22        [butuh, game, budget, mepet, ambil, radeon]       AMD
23  [buat, banding, gaming, utama, game, baru, mac...    NVIDIA
24  [dlss, memang, lebih, bagus, fsr, maka, fsr, a...   Lainnya

In [ ]:
# Modeling (Naive Bayes / SVM / LSTM)

In [ ]:
# tokenized_commyt.to_csv("data_pandas.csv", index=False)

In [ ]:
# Normalization (Normalisasi Kata)
# Mengubah kata tidak baku/slang menjadi baku

# def load_slang_dict(path):
  # df = pd.read_csv(path)
  # df = pd.read_csv(path)

  # df["slang"] = df["slang"].str.lower()
  # df["formal"] = df["formal"].str.lower()

  # return dict(zip(df["slang"], df["formal"]))

In [ ]:
# def normalize_tokens(tokenized_commyt, slang_dict):
#   normalized = []

#   for sentence in tokenized_commyt:
#     normalized_sentence = []

#     for token in sentence:
#       if token in slang_dict:
#         normalized_sentence.append(slang_dict[token])
#       else:
#         normalized.append(token)
#     return normalized

# normal = tokenized_commyt["comment"] = yt["comment"].apply(normalize_tokens)
# normal = normalize_tokens(tokenized_commyt, load_slang_dict("/content/drive/MyDrive/Colab Notebooks/AnalisisSentimen/AnalisisSentimen_3/Dataset/slangindo/slang_indo.csv"))
# tokenized_commyt.head(50)

In [ ]:
# slang_dict = load_slang_dict("/content/drive/MyDrive/Colab Notebooks/AnalisisSentimen/AnalisisSentimen_3/Dataset/slangindo/slang_indo.csv")

# normal = normalize_tokens(tokenized_commyt, slang_dict)
# normal = normallized_commyt["comment"] = normal[""]
# yt["normalized"] = yt["tokens"].apply(lambda x: normalize_tokens(x, slang_dict))
# normal.head()
# print(normal)

In [ ]:
# def load_slang_dict(path):
#     slang_df = pd.read_csv(path)

    # pastikan kolom sesuai
    # slang_dict = dict(zip(slang_df['slang'], slang_df['formal']))

    # return slang_dict

# load kamus
# slang_dict = load_slang_dict('/content/drive/MyDrive/Colab Notebooks/AnalisisSentimen/AnalisisSentimen_3/Dataset/slangindo/slang_indo.csv')

In [ ]:
# def normalize_tokens(tokens, slang_dict):

# def normalize_tokens(tokenized_commyt, slang_dict):

#     normalized = []

#     for word in tokenized_commyt:
#         if word in slang_dict:
#             normalized.append(slang_dict[word])
#         else:
#             normalized.append(word)

#     return normalized

In [ ]:
# df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/AnalisisSentimen/AnalisisSentimen_3/Dataset/data_pandas.csv')

In [ ]:
# import ast

# df['tokens'] = df['tokens'].apply(ast.literal_eval)
# df['comment'] = df['comment'].apply(ast.literal_eval)
# norr.head()

In [ ]:
# nor = df['normalized'] = df['comment'].apply(lambda x: normalize_tokens(x, slang_dict))

# nor_satu = yt['normalized'] = yt['comment'].apply(lambda x: normalize_tokens(x, slang_dict))
# nor_satu.head()

In [ ]:
# nor = df['normalized'] = df['comment'].apply(lambda x: normalize_tokens(x, slang_dict))
# yt['normalized'] = yt['comment'].apply(lambda x: normalize_tokens(x, slang_dict))
# nor.head(50)